<?php


function carpoolingmod_init() {
	drupal_add_css(drupal_get_path('module', 'carpoolingmod').'/carpoolingmod.css');
	
	if(arg(0) == 'Catalog'){
		drupal_add_library('system', 'ui.sortable');
	}
}

function carpoolingmod_permission() {
  return array(
    'setup carpooling pref' => array(
      'title' => t('setup carpooling pref'),
    ),
    'join ride' => array(
      'title' => t('join ride'),
    ),
  );
}

function carpoolingmod_pref_setup_page_title(){
	return t('Carpooling Preference');
}

function carpoolingmod_myrides_page_title(){
	return t('My Rides');
}

function carpoolingmod_rides_carpooling_page_title(){
	return t('Rides and car pooling');
}

function carpoolingmod_rides_carpooling_look_for_page_title(){
	return t('Looking for a ride');
}

function carpoolingmod_rides_carpooling_offer_page_title(){
	return t('Offering a ride');
}

function carpoolingmod_join_ride_form_title($account){
	return t('Join !user\'s ride', array('!user' => $account->name));
}

function carpoolingmod_addmycar_ride_form_title($account){
	return t('Add !user to my car', array('!user' => $account->name));
}

function carpoolingmod_removemycar_ride_form_title($account){
	return t('Remove !user from my car', array('!user' => $account->name));
}

function carpoolingmod_leave_ride_form_title($account){
	return t('Remove myself from !user\'s ride', array('!user' => $account->name));
}

/**
 * @file
 * Provides a views style plugin for FullCalendar
 */

function carpoolingmod_menu() {
  $items = array();

  $items['registration/carpooling-pref'] = array(
    'title callback' => 'carpoolingmod_pref_setup_page_title',
    'page callback' => 'carpoolingmod_pref_setup_page',
    'access callback' => 'user_access',
    'access arguments' => array('setup carpooling pref'),
    'file' => 'carpoolingmod.admin.php',
    'type' => MENU_CALLBACK,
  );

  $items['MyRides'] = array(
    'title callback' => 'carpoolingmod_myrides_page_title',
    'page callback' => 'carpoolingmod_myrides_page',
    'access callback' => 'user_access',
    'access arguments' => array('setup carpooling pref'),
    'file' => 'carpoolingmod.admin.php',
    'type' => MENU_CALLBACK,
  );

  $items['rides-carpooling'] = array(
    'title callback' => 'carpoolingmod_rides_carpooling_page_title',
    'page callback' => 'carpoolingmod_offer_ride_page',
    'access callback' => 'user_access',
    'access arguments' => array('setup carpooling pref'),
    'file' => 'carpoolingmod.pages.php',
    'type' => MENU_CALLBACK,
  );

  $items['rides-carpooling/offer-ride'] = array(
    'title callback' => 'carpoolingmod_rides_carpooling_offer_page_title',
    'page callback' => 'carpoolingmod_offer_ride_page',
    'access callback' => 'user_access',
    'access arguments' => array('setup carpooling pref'),
    'file' => 'carpoolingmod.pages.php',
    'type' => MENU_LOCAL_TASK,
	'#weight' => 1,
  );

  $items['rides-carpooling/look-for-ride'] = array(
    'title callback' => 'carpoolingmod_rides_carpooling_look_for_page_title',
    'page callback' => 'carpoolingmod_look_for_ride_page',
    'access callback' => 'user_access',
    'access arguments' => array('join ride'),
    'file' => 'carpoolingmod.pages.php',
    'type' => MENU_LOCAL_TASK,
	'#weight' => 0,
  );

  $items['carpool/join/%user'] = array(
    'title callback' => 'carpoolingmod_join_ride_form_title',
    'title arguments' => array(2),
    'page callback' => 'carpoolingmod_join_ride_form_page',
    'page arguments' => array(2),
    'access callback' => 'carpoolingmod_join_ride_form_access',
    'access arguments' => array(2),
    'file' => 'carpoolingmod.pages.php',
    'type' => MENU_CALLBACK,
  );

  $items['carpool/addmycar/%user'] = array(
    'title callback' => 'carpoolingmod_addmycar_ride_form_title',
    'title arguments' => array(2),
    'page callback' => 'carpoolingmod_addmycar_ride_form_page',
    'page arguments' => array(2),
    'access callback' => 'carpoolingmod_addmycar_ride_form_access',
    'access arguments' => array(2),
    'file' => 'carpoolingmod.pages.php',
    'type' => MENU_CALLBACK,
  );

  $items['carpool/removemycar/%user'] = array(
    'title callback' => 'carpoolingmod_removemycar_ride_form_title',
    'title arguments' => array(2),
    'page callback' => 'carpoolingmod_removemycar_ride_form_page',
    'page arguments' => array(2),
    'access callback' => 'carpoolingmod_removemycar_ride_form_access',
    'access arguments' => array(2),
    'file' => 'carpoolingmod.admin.php',
    'type' => MENU_CALLBACK,
  );

  $items['carpool/leave/%user'] = array(
    'title callback' => 'carpoolingmod_leave_ride_form_title',
    'title arguments' => array(2),
    'page callback' => 'carpoolingmod_leave_ride_form_page',
    'page arguments' => array(2),
    'access callback' => 'carpoolingmod_leave_ride_form_access',
    'access arguments' => array(2),
    'file' => 'carpoolingmod.admin.php',
    'type' => MENU_CALLBACK,
  );

  $items['catalog/update-position'] = array(
    'page callback' => 'carpoolingmod_update_position_page',
    'access callback' => 'user_access',
    'access arguments' => array('administer nodes'),
    'file' => 'carpoolingmod.admin.php',
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

function carpoolingmod_form_alter(&$form, $form_state, $form_id){
	if(isset($form['field_weight']) && $form['field_weight']){
		$form['field_weight']['#access'] = false;
	}
}

function carpoolingmod_user_view($account, $view_mode, $langcode){
	global $user;
	if($view_mode == 'full' && $user->uid == $account->uid && (user_access('setup carpooling pref') || user_access('join ride'))){
		$data = carpoolingmod_load_pref($account);
		
//		if($data && ($data['type'] == 'offer' || $data['type'] == 'lookfor')){
			$account->content['transportation'] = array(
				'#type' => 'markup',
				'#markup' => '<ul class="item-list"><li>'.l(t('Car Pooling Preference Setting'), 'MyRides').'</li>
					<li>'.l(t('Users of Offering Ride'), 'rides-carpooling/offer-ride').'</li>
					<li>'.l(t('Users of Looking for Ride'), 'rides-carpooling/look-for-ride').'</li></ul>',
			);
//		}
	}
}

function carpoolingmod_join_ride_form_access($account){
	global $user;
  $semester = _get_current_semester();
	$joined = db_query("select created from {carpooling_ride} where join_uid=:join_uid and offer_uid=:offer_uid and semester=:semester", array(':join_uid' => $user->uid, ':offer_uid' => $account->uid, ':semester' => $semester))->fetchField();
	
	$data = carpoolingmod_load_pref($account);
	
	if(!$joined && user_access('join ride') && $data && $data['type'] == 'offer' && $data['remaining_seats'] > 0){
		return true;
	}else{
		return false;
	}
}

function carpoolingmod_addmycar_ride_form_access($account){
	global $user;
  $semester = _get_current_semester();
	$data = carpoolingmod_load_pref($user);
	
	$joined = db_query("select created from {carpooling_ride} where join_uid=:join_uid and offer_uid=:offer_uid and semester=:semester", array(':join_uid' => $account->uid, ':offer_uid' => $user->uid, ':semester' => $semester))->fetchField();
	
	if(!$joined && user_access('join ride', $account) && $data && $data['type'] == 'offer' && $data['remaining_seats'] > 0){
		return true;
	}else{
		return false;
	}
}

function carpoolingmod_removemycar_ride_form_access($account){
	global $user;
  $semester = _get_current_semester();
	$data = carpoolingmod_load_pref($user);
	
	$joined = db_query("select created from {carpooling_ride} where join_uid=:join_uid and offer_uid=:offer_uid and semester=:semester", array(':join_uid' => $account->uid, ':offer_uid' => $user->uid, ':semester' => $semester))->fetchField();
	
	if($joined && user_access('join ride', $account) && $data && $data['type'] == 'offer'){
		return true;
	}else{
		return false;
	}
}

function carpoolingmod_leave_ride_form_access($account){
	global $user;
  $semester = _get_current_semester();
	$joined = db_query("select created from {carpooling_ride} where join_uid=:join_uid and offer_uid=:offer_uid and semester=:semester", array(':join_uid' => $user->uid, ':offer_uid' => $account->uid, ':semester' => $semester))->fetchField();
	$data = carpoolingmod_load_pref($account);
	
	if($joined && user_access('join ride')){
		return true;
	}else{
		return false;
	}
}

function carpoolingmod_date_options(){
	return array(
		7 => t('Sunday'),
		1 => t('Monday'),
		2 => t('Tuesday'),
		3 => t('Wednesday'),
		4 => t('Thursday'),
		5 => t('Friday'),
		6 => t('Saturday'),
	);
}

function carpoolingmod_time_options(){
	return array(
		'morning' => t('Morning'),
		'noon' => t('Noon'),
		'evening' => t('Evening'),
		'night' => t('Night'),
	);
}


function carpoolingmod_format_datetime($dates, $time){
	$dateopts = carpoolingmod_date_options();
	$timeopts = carpoolingmod_time_options();

	$html = '';
	if($dates){
		$datestrs = array();
		if(!is_array($dates)){
			$dates = explode(',', $dates);
		}
		
		foreach($dates as $d){
			$datestrs[] = $dateopts[$d];
		}
		
		$html = '<b>'.t('Date').':</b> '.implode(', ', $datestrs).'<br/><b>'.t('Time').':</b> '.$timeopts[$time];
	}
	
	return $html;
}

function carpoolingmod_load_pref($account = null){
	if(!$account){
		global $user;
		$account = $user;
	}

  $semester = _get_current_semester();
	
	$data = db_query("select * from {carpooling_pref} where uid=:uid and semester=:semester", array(':uid' => $account->uid, ':semester' => $semester))->fetchAssoc();
	
	if($data){
		$data['departureday'] = $data['departureday'] ? explode(',', $data['departureday']) : array();
		$data['returnday'] = $data['returnday'] ? explode(',', $data['returnday']) : array();
	}
	
	return $data;
}

function _get_current_semester() {
  module_load_include('inc', 'arava_registration', 'MySemesterAPI.class');
  $mySemesterAPI = new MySemesterAPI();
  return $mySemesterAPI->getCurrentSemester(true);
}