<?php

/**
 * Implements hook_menu().
 * @return mixed
 */
function arava_registration_menu() {

	$items['registration/course'] = array(
		'title' => t('Course Selection'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('arava_registration_course'),
		'access arguments' => array('signup to courses and accommodation'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'arava_registration.courses.inc'
	);

	$items['registration/accommodation'] = array(
		'title' => t('Accomodation Selection'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('arava_registration_accommodation'),
		'access arguments' => array('signup to courses and accommodation'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'arava_registration.accommodation.inc'
	);



	return $items;
}

/**
 * Implements hook_permission().
 */
function arava_registration_permission() {
	return array(
		'signup to courses and accommodation' => array(
			'title' => t('Signup to courses and accommodation'),
		)
	);
}

function _arava_registration_generate_view($view_name, $display_name) {
	$view = views_get_view($view_name);
	$view->set_display($display_name);
	$view->pre_execute();
	return $view->render();
}



